#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE="${ENV_FILE:-.env.local}"

banner "Founder Voice local provider setup"

stage "Local app URL"
say "We will create or update .env.local. It is ignored by git."
ask NEXT_PUBLIC_APP_URL "Local app URL [usually http://localhost:3000]:"
write_env NEXT_PUBLIC_APP_URL "$NEXT_PUBLIC_APP_URL"

stage "Supabase project"
say "Create or select the project that stores accounts and all user-owned data."
open_url "https://supabase.com/dashboard/projects"
step "Open your project, then go to Project Settings → API."
step "Copy the Project URL, the anon/publishable key, the service_role key, and the project reference."
ask NEXT_PUBLIC_SUPABASE_URL "Paste the Project URL:"
ask NEXT_PUBLIC_SUPABASE_ANON_KEY "Paste the anon or publishable key:"
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste the service_role key (server only):"
ask SUPABASE_PROJECT_ID "Paste the project reference:"
write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
write_env SUPABASE_PROJECT_ID "$SUPABASE_PROJECT_ID"
step "Run 'pnpm supabase db reset' for local development, or 'pnpm supabase db push' after linking the hosted project."
pause "Press Enter when the migration has been applied."

stage "Google OAuth in Supabase"
say "Google client credentials remain in Google Cloud and Supabase; they are not application environment variables."
open_url "https://console.cloud.google.com/apis/credentials"
step "Create an OAuth 2.0 Client ID of type Web application."
step "Add the local app URL as an Authorized JavaScript origin."
step "Add https://<your-project-ref>.supabase.co/auth/v1/callback as an Authorized redirect URI."
step "Copy the Google client ID and client secret, then open Supabase Authentication → Providers → Google."
step "Enable Google and save those two Google values there."
pause "Press Enter when Google sign-in is enabled in Supabase."

stage "OpenAI"
open_url "https://platform.openai.com/api-keys"
step "Create a project API key for this app and copy it once."
ask_secret OPENAI_API_KEY "Paste the OpenAI API key:"
write_env OPENAI_API_KEY "$OPENAI_API_KEY"

stage "ElevenLabs"
open_url "https://elevenlabs.io/app/settings/api-keys"
step "Create an API key limited to this application and copy it."
ask_secret ELEVENLABS_API_KEY "Paste the ElevenLabs API key:"
write_env ELEVENLABS_API_KEY "$ELEVENLABS_API_KEY"

stage "Resend"
open_url "https://resend.com/api-keys"
step "Create an API key. Before production delivery, verify the sending domain in Resend Domains."
ask_secret RESEND_API_KEY "Paste the Resend API key:"
write_env RESEND_API_KEY "$RESEND_API_KEY"

stage "Inngest"
open_url "https://app.inngest.com/"
step "Create or select the app, then open its Connect / Keys settings."
step "Copy the event key and signing key for the local environment."
ask_secret INNGEST_EVENT_KEY "Paste the Inngest event key:"
ask_secret INNGEST_SIGNING_KEY "Paste the Inngest signing key:"
write_env INNGEST_EVENT_KEY "$INNGEST_EVENT_KEY"
write_env INNGEST_SIGNING_KEY "$INNGEST_SIGNING_KEY"

stage "PostHog (optional for the foundation)"
open_url "https://us.posthog.com/project/settings"
step "Open Project Settings → Project details and copy the Project API Key when analytics is ready."
ask NEXT_PUBLIC_POSTHOG_KEY "Paste the PostHog project API key, or leave blank for now:"
ask NEXT_PUBLIC_POSTHOG_HOST "Paste the PostHog host, or use https://us.i.posthog.com:"
write_env NEXT_PUBLIC_POSTHOG_KEY "$NEXT_PUBLIC_POSTHOG_KEY"
write_env NEXT_PUBLIC_POSTHOG_HOST "${NEXT_PUBLIC_POSTHOG_HOST:-https://us.i.posthog.com}"

finish
